### ISSUE TITLE
Uncaught C# exception brings down node.js

### ISSUE THREAD

**Issue by oldsaltycrab** [tjanczuk/edge#226] opened 2015-01-08 00:47 UTC
Hello, 

Using edge.js 0.9.3, I've encountered a situation where an exception is thrown in a C# binding function which causes node.js to immediately exit.  If I attempt to access a member of the dynamic object that does not exist, without catching the exception, this will happen.  Any other exceptions I can contrive/throw inside the binding function are caught by edge's unhandled exception catch.  

In the below example, the input object does not contain a SomeMissingProperty member, so an exception will be thrown on this line: `long input_number = Convert.ToInt64(input.SomeMissingProperty);`

```
        public async Task<object> SomeBindingMethod(dynamic input)
        {
            return await Task.Run<object>(() =>
            {
                long input_number = Convert.ToInt64(input.SomeMissingProperty);
                Results results = CalculateStuff(input_number);
                return results;
            });
        }
```

If I run within Visual Studio, I can see a series of exceptions being thrown.  The first exception is the expected `RuntimeBinderException`, thrown when a missing property is attempted to be accessed on a dynamic object.  The second exception will be a `System.Reflection.TargetInvocationException` which has an InnerException of type `System.NotSupportedException: The invoked member is not supported in a dynamic assembly.`.

If I wrap the offending code in a try/catch block and simply rethrow the caught Exception, node/edge handles it properly.  

Thanks

**Comment by tjanczuk** [comment] 2015-01-08 05:22
Can you provide a complete repro? I am unable to reproduce this behavior with the following code:

```
var hello = require('edge').func(function () {/*
    async (dynamic input) => 
    { 
        return await Task.Run<object>(() =>
        {
            return (object)input.bar;
        });
    }
*/});

hello({ foo: 12 }, function (error, result) {
    if (error) throw error;
    console.log(result);
});
```

When I run it, I get the error passed correctly to the callback function in JS:

```
/Users/tomek/projects/edge/adhoc/226.js:14
    if (error) throw error;
                     ^
Error: `System.Dynamic.ExpandoObject' does not contain a definition for `bar'
```

**Comment by oldsaltycrab** [comment] 2015-01-19 21:52
Hi Tomasz, thanks for the reply.  

On a clean slate, with my node_modules looking like this:
```
├─┬ edge@0.9.3
│ └── edge-cs@0.2.7
└── http@0.0.0
```
My single javascript file looks like this:

```
var hello = require('edge').func(function () {/*
    async (dynamic input) => 
    { 
        return await Task.Run<object>(() =>
        {
            Console.WriteLine(input.bar + " - from C#");
            return (object)input.bar;
        });
    }
*/});

var http = require('http');
http.createServer(function (req, res) {

  hello({ foo: 12 }, function (error, result) {
        if (error) throw error;
        console.log(result);
    });


  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World - vanilla node\n');  
}).listen(3000, '127.0.0.1');
console.log('Server running at http://127.0.0.1:3000/');
```

If I simply run that file in node (have tried node versions: v0.10.22, v0.10.32 and v0.10.35), visit http://localhost:3000, node crashes with:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ClrFunc.MarshalCLRObjectToV8(Handle<v8::Object>* , Object netdata)
   at ClrFunc.MarshalCLRToV8(Handle<v8::Value>* , Object netdata)
   at ClrFunc.MarshalCLRObjectToV8(Handle<v8::Object>* , Object netdata)
   at ClrFunc.MarshalCLRToV8(Handle<v8::Value>* , Object netdata)
   at ClrFunc.MarshalCLRObjectToV8(Handle<v8::Object>* , Object netdata)
   at ClrFunc.MarshalCLRToV8(Handle<v8::Value>* , Object netdata)
   at ClrFunc.MarshalCLRObjectToV8(Handle<v8::Object>* , Object netdata)
   at ClrFunc.MarshalCLRExceptionToV8(Handle<v8::Value>* , Exception exception)
   at ClrFuncInvokeContext.CompleteOnV8Thread(Handle<v8::Value>* )
   at ClrFuncInvokeContext.CompleteOnV8ThreadAsynchronous()
   at clrActionContext.ActionCallback(Void* data)
   at continueOnV8Thread(uv_async_s* handle, Int32 status)
```

Thanks

**Comment by snaveenkumareee** [comment] 2015-03-23 04:37
Facing the same error. 
Env details: 
node: 0.12.0
OS: windows 7 64 bit
edge: 0.10.1

**Comment by snaveenkumareee** [comment] 2015-04-03 09:10
Can you please provide the fix for this issue. The above work around is not working for all scenarios.

**Comment by Jeff-Lewis** [comment] 2016-09-22 16:47
The ` The invoked member is not supported in a dynamic assembly` error is the default error from .NET when a `dynamic` `ExpandoObject` does not have the property you are looking for. In your case, property `input.bar` does not exist, only `input.foo` does. 

See [here for more info](http://stackoverflow.com/questions/2998954/test-if-a-property-is-available-on-a-dynamic-variable) on checking if properties exist on dynamic objects.

Why it crashes node? I'm not sure but It might be related to the version of .NET or your .NET machine config. Also, you can just add a `try{} catch{}` at the top to encapsulate the C#. 

``` c#
return await Task.Run<object>(() =>
        {
            try{
                Console.WriteLine(input.bar + " - from C#");            
                return (object)input.bar;
            } catch (Exception ex){
                Console.WriteLine(ex);
            }
        });
```

**Closed** 2024-10-01 20:47 UTC
