### ISSUE TITLE
Support io.js

### ISSUE THREAD

**Issue by bpasero** [tjanczuk/edge#235] opened 2015-02-10 16:43 UTC
Any plans to support edge for io.js?

**Comment by blackshadev** [comment] 2015-02-11 13:16
I would like to see this too. I don't have a proper setup to compile it myself, so a precopiled version for IO.JS 1.2.0 would be nice.

**Comment by waynebloss** [comment] 2015-02-13 00:02
[Microsoft just joined Joyent's new Node.js Foundation](http://www.joyent.com/about/press/joyent-moves-to-establish-nodejs-foundation), but I hope that doesn't stop them from supporting io.js.

It [seems like](https://news.ycombinator.com/item?id=9027393) many people aren't too happy with Joyent and are planning on using io.js, so if the vast majority of users are going in that direction then I'm sure the good folks at Microsoft will want io.js support to happen across their enterprise and all of their new open source projects.

**Comment by blackshadev** [comment] 2015-02-13 09:38
Edge can already be compiled for io.js, the problem is that I never not got anything to compile (nodejs or io.js) because for some reason). Maybe I will try it again later, I just hoped that the guys from edge would be so nice and precompile it for iojs for us.

**Comment by tjanczuk** [comment] 2015-02-21 23:18
I am *the guys from edge* ;). My priority right now is to release a version with support for Node 0.12. I have not looked at supporting io.js yet, I would be happy to do it if and when there is sufficient demand. @bpasero out of curiosity, what's your need for io.js?

**Comment by studiochris** [comment] 2015-02-25 20:31
@tjanczuk For better or worse, both [nwjs/nw.js](https://github.com/nwjs/nw.js/) and [atom/atom-shell](https://github.com/atom/atom-shell/) have already begun the switch to io.js (both being projects I am using or am planning to use with edge). 

I currently use edge in the 0.8.6 "longer-term support release" of nwjs (was node-webkit). I wasn't able to move forward into newer versions of nwjs for these projects because of a lack of edge for node 0.11. Unless the node 0.12 version is also compatible with io.js, it looks like that's where I'll stay stuck until I find another solution (or just go full .NET where required).

**Comment by jesstelford** [comment] 2015-02-26 05:22
demand-for-iojs++;

@tjanczuk 

> what's your need for io.js?

io.js:
* [is more performant](https://raygun.io/blog/2015/02/node-js-performance-node-js-vs-io-js)
* uses a more up-to-date v8 engine [4.1.0.14](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#notable-changes-2) vs [3.28.73 for node 0.12](https://github.com/joyent/node/wiki/API-changes-between-v0.10-and-v0.12)
* [supports more es6 language features out of the box](https://iojs.org/en/es6.html)
* has [a LOT of other fixes and improvements upon node](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md)

**Comment by Oceanswave** [comment] 2015-02-28 03:38
+1 would love to see this as well

**Comment by jesstelford** [comment] 2015-03-04 00:29
Linking to the io.js master thread: iojs/io.js#456

**Comment by jjordy** [comment] 2015-03-13 19:11
+1 Attempted to compile it myself a couple of weeks ago. Failed miserably

**Comment by romovs** [comment] 2015-03-19 23:39
+1
io.js support would be definitely welcome.

**Comment by Wortex17** [comment] 2015-03-22 13:09
+1
io.js is taking speed

**Comment by JediMindtrick** [comment] 2015-04-03 17:09
+1, want to use it in conjunction with nw.js (formerly node-webkit)

**Comment by waynebloss** [comment] 2015-05-15 15:12
I would like to use Edge.js with atom/electron (formerly atom-shell).

**Comment by JediMindtrick** [comment] 2015-05-15 16:50
Since it looks like io.js is going to end up merging back into node, this isn't all that important to me any more.

**Comment by Oceanswave** [comment] 2015-05-15 16:53
what @JediMindtrick said... as long as edge works with future versions of node after the merge.

**Comment by tjanczuk** [comment] 2015-05-15 17:39
I am committed to supporting edge with future versions of node, including the one after iojs merge.

**Comment by waynebloss** [comment] 2015-05-15 17:46
Good to hear :+1:

**Comment by Wortex17** [comment] 2015-05-17 11:10
@JediMindtrick 
> Since it looks like io.js is going to end up merging back into node, this isn't all that important to me any more.

Are there any *news* I have missed? I know that iojs wants to merge back, as that was its plan from the beginning. Are there new events that indicate that will happen in **near future**?

Otherwise
>committed to supporting edge with future versions of node, including the one after iojs merge

means "not support iojs" and "this issue will become irrelevant when/if they merge"

Sorry if I'm a tad bit too nervous about this, but I'd hate to regret having migrated to the more active platform.

**Comment by Wortex17** [comment] 2015-05-17 11:23
Ah, ok, i found it [here](https://github.com/nodejs/io.js/issues/1664) and [here](https://github.com/nodejs/node) that they are actually already working on the merge. I did not know that they already were in dry docks with all that policy management.
Seems like there are still many months of waiting to come but I hope it proceeds well.

**Comment by romovs** [comment] 2015-05-17 13:07
@waynebloss
> I would like to use Edge.js with atom/electron (formerly atom-shell).

[Here is](https://github.com/cloudbeat-io/electron-edge) a quick hack for Electron >= 0.25.0 < 0.27.0
(should be build against `--target=0.25.0 --dist-url=https://atom.io/download/electron`) 
I haven't tested everything, so take it as is.

**Comment by JediMindtrick** [comment] 2015-05-24 11:22
@romovs Thanks for doing this!

**Comment by wouterverweirder** [comment] 2015-07-11 13:59
[Future Node.js releases will be based on io.js](https://github.com/nodejs/io.js) - would be nice if edge makes to move to io.js :-)

**Closed** 2024-06-05 15:31 UTC
