### ISSUE TITLE
passing large string (json object) to edge messes the string up (SOH char at the end)

### ISSUE THREAD

**Issue by telmocsa** [tjanczuk/edge#310] opened 2015-08-26 17:35 UTC
Hello.
Something is happening occasionally (two out of three times) when passing a large string (about 200k chars) from C# to Node js function. We see that some times this string gets an ending SOH char that breaks stuff in the javascript node function invoked from C#.

This is basically what we're doing:
var renderer = EdgeJs.Edge.Func(@"return require('loadtemplate.js')");
var result = (string)renderer(new { fullPath = this.ScriptFullPath, templateName = this.Name, template = Regex.Unescape(templateScript), data = json/_this gets the extra SOH inside loadtemplate.js_/ }).Result;

Thank you!
Telmo

**Comment by tsnordin** [comment] 2015-09-22 17:41
We're seeing the same issue on our end too.  It doesn't happen on all of our environments, but on certain ones we're seeing SOH being appended to the end of large JSON strings being passed back from C# into our javascript code which then breaks it as JSON.parse() fails.  It's strange though because the data being returned is exactly the same between environments, yet the issue only manifests it self on certain ones.  When it does happen though it happens consistently.

My workaround for now is calling replace on the string to clear up SOH before parsing it:

data = JSON.parse(data.replace('\u0001', ''));

Would love to see a proper fix for this though!

**Comment by tjanczuk** [comment] 2015-09-22 18:21
@tsnordin could you provide a sample string that causes this issue?

**Comment by tsnordin** [comment] 2015-09-22 18:55
Hey @tjanczuk.  Can't really post the entire string from our environment due to privacy concerns, but here's tail end of it where you can see the SOH shows up after the closing bracket but before the closing quote.

]"

I also can't readily reproduce this issue with a simple sample.  As mentioned above this issue only manifests on certain environments but not others.  Though the configuration between environments is the same and it's the same string being returned.

As for the string itself it's 84987 characters long.  If there's any other info I can give to help please let me know.

**Comment by tianhuat** [comment] 2015-12-24 09:00
I have met with this issue as well...

**Comment by EricSmekens** [comment] 2016-03-29 13:46
Also encountered this with a message length of around 100000 chars.
But the thing I also observed, is that it seem to happen randomly. Sometimes it works.

**Comment by EricSmekens** [comment] 2016-05-09 20:50
Reproduceable with:

```
// Overview of edge.js: http://tjanczuk.github.com/edge

var edge = require('../lib/edge');

var hello = edge.func(function () {/*
	async (input) => 
	{
		
		string bigString = "";
		int i = 0;
		for (i = 0; i < 85000; i++) {
			bigString += "h";
		}

		return bigString;
	}
*/});

hello(null, function (error, result) {
	if (error) throw error;
	console.log('-----> In node.js:');
	console.log(result);
});
```

**Comment by tagplus5** [comment] 2016-05-09 23:38
I work with big return strings 
node 4.4.4
edge.js 5.0.3-pre
mono 4.2.3

@EricSmekens, you code even with **i < **850000** work without any bugs

```
// Overview of edge.js: http://tjanczuk.github.com/edge
var edge = require('edge');
var hello = edge.func(function () {/*
    async (input) => 
    {
        string bigString = "";
        int i = 0;
        for (i = 0; i < 850000; i++) {
            bigString += "h";
        }
        return bigString;
    }
*/});

hello(null, function (error, result) {
    if (error) throw error;
    console.log('-----> In node.js:');
    console.log(result);
});
```

**Comment by EricSmekens** [comment] 2016-05-10 06:07
I will test that when I'm on my laptop again.
I was using 
- Node 5.9.1
- Edge 5.0.3-pre
- Windows 10, .NET 4.6 I believe.

**Closed** 2024-10-01 19:56 UTC
